### ISSUE TITLE
Torus.init should be synchronization function

### ISSUE THREAD

**Issue by croe** [torusresearch/torus-embed#146]
**Is your feature request related to a problem? Please describe.**
We are developing an SDK using this library.
I want to know the login status (getUserInfo) of Torus at the SDK initialization point, but I cannot execute the function such as getUserInfo synchronously because torus.init is an async function.
Is it possible to change torus.init to synchronization function?
Otherwise, there're some problems such as, user executes the login process before the initialization of Torus-embed.
Also, even if you execute torus.init before the Login function, there is a problem left that init is executed multiple times because you can't catch the login status.

**Describe the solution you'd like**
torus.init to be synchronization function

**Comment by chaitanyapotti** [comment]
Hello @croe ,

torus.init() can't be a synchronous function. It needs to be async because it makes some network calls etc.
The order of functions to call in torus sdk is
```
const torus = new Torus()
await torus.init()
await torus.login()
```
So, please mark your function async and await the initialization before calling login.
Please refer to some [examples](https://github.com/torusresearch/torus-embed/blob/master/examples/vue-app/src/App.vue#L81)
